on:
  pull_request:
  push:
    branches:
      - main
name: 'Quality assurance'
jobs:
  qa-code:
    name: 'Check code quality'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: eaudeweb/drupal-install-action@v1.0
        with:
          dev: true

      - uses: eaudeweb/drupal-code-qa-action@2.x
        with:
          phplint: 'true'
          phpmd: 'true'
          phpcs: 'true'
          phpstan: 'false'